INFO || 26-Jan-24 02:40:15 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 02:41:40 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 02:53:44 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 02:55:24 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 02:57:04 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 02:57:46 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 26-Jan-24 04:31:07 || Processing request...
INFO || 26-Jan-24 04:32:46 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 04:32:48 || Processing request...
INFO || 26-Jan-24 04:39:43 || mathematics english chemistry physics geography computer studies
INFO || 26-Jan-24 04:39:43 || science teaching public speaking reading gaming writing travelling technology astronomy reading and learnng robotics metal detecting
INFO || 26-Jan-24 04:39:43 || Beginning to run the recommender script
INFO || 26-Jan-24 04:39:43 || Recommender model loaded and running
INFO || 26-Jan-24 04:39:43 || Processing request...
CRITICAL || 26-Jan-24 04:40:02 || Something came up, please rerun the system...
INFO || 26-Jan-24 04:40:02 || Recommender system has run
ERROR || 26-Jan-24 04:40:02 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
ERROR || 26-Jan-24 04:53:06 || Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'static'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 295, in course_recommendation
    return render(request, 'academia_app/course_recommendation_page.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\engine.py", line 175, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 6: 'static'. Did you forget to register or load this tag?
INFO || 26-Jan-24 05:03:18 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:04:08 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:04:20 || Beginning to run the recommender script
INFO || 26-Jan-24 05:04:20 || Recommender model loaded and running
CRITICAL || 26-Jan-24 05:04:20 || Something came up, please rerun the system...
INFO || 26-Jan-24 05:04:20 || Recommender system has run
ERROR || 26-Jan-24 05:04:21 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 05:04:58 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:05:28 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:06:35 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:06:48 || Beginning to run the recommender script
INFO || 26-Jan-24 05:06:48 || Recommender model loaded and running
INFO || 26-Jan-24 05:06:48 || Processing request...
INFO || 26-Jan-24 05:07:11 || Recommender system has run
INFO || 26-Jan-24 05:08:08 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:13:53 || Beginning to run the recommender script
INFO || 26-Jan-24 05:13:53 || Recommender model loaded and running
INFO || 26-Jan-24 05:13:53 || Processing request...
INFO || 26-Jan-24 05:14:16 || Recommender system has run
INFO || 26-Jan-24 05:16:31 || Beginning to run the recommender script
INFO || 26-Jan-24 05:16:31 || Recommender model loaded and running
INFO || 26-Jan-24 05:16:31 || Processing request...
INFO || 26-Jan-24 05:17:12 || Recommender system has run
INFO || 26-Jan-24 05:18:12 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 05:18:19 || Beginning to run the recommender script
INFO || 26-Jan-24 05:18:19 || Recommender model loaded and running
INFO || 26-Jan-24 05:18:19 || Processing request...
INFO || 26-Jan-24 05:18:58 || Recommender system has run
INFO || 26-Jan-24 07:58:16 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:02:57 || Beginning to run the recommender script
INFO || 26-Jan-24 08:02:57 || Recommender model loaded and running
INFO || 26-Jan-24 08:02:57 || Processing request...
CRITICAL || 26-Jan-24 08:03:48 || Something came up, please rerun the system...
INFO || 26-Jan-24 08:03:48 || Recommender system has run
ERROR || 26-Jan-24 08:03:48 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 08:05:16 || Beginning to run the recommender script
INFO || 26-Jan-24 08:05:16 || Recommender model loaded and running
INFO || 26-Jan-24 08:05:16 || Processing request...
INFO || 26-Jan-24 08:05:59 || Recommender system has run
INFO || 26-Jan-24 08:06:47 || Beginning to run the recommender script
INFO || 26-Jan-24 08:06:47 || Recommender model loaded and running
INFO || 26-Jan-24 08:06:47 || Processing request...
INFO || 26-Jan-24 08:07:26 || Recommender system has run
INFO || 26-Jan-24 08:08:01 || Beginning to run the recommender script
INFO || 26-Jan-24 08:08:01 || Recommender model loaded and running
INFO || 26-Jan-24 08:08:01 || Processing request...
INFO || 26-Jan-24 08:08:50 || Recommender system has run
INFO || 26-Jan-24 08:13:13 || Beginning to run the recommender script
INFO || 26-Jan-24 08:13:13 || Recommender model loaded and running
INFO || 26-Jan-24 08:13:13 || Processing request...
INFO || 26-Jan-24 08:13:49 || Recommender system has run
INFO || 26-Jan-24 08:16:03 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
ERROR || 26-Jan-24 08:27:15 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 142, in predict_probability
    return render(request, 'your_input_form_template.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: your_input_form_template.html
INFO || 26-Jan-24 08:28:01 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:28:28 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:28:36 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 08:28:46 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 142, in predict_probability
    return render(request, 'predicted_prob.html.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html.html
ERROR || 26-Jan-24 08:28:48 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 142, in predict_probability
    return render(request, 'predicted_prob.html.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html.html
INFO || 26-Jan-24 08:29:15 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 08:29:19 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 143, in predict_probability
    return render(request, 'predicted_prob.html.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html.html
INFO || 26-Jan-24 08:29:50 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:29:55 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 08:29:59 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 143, in predict_probability
    return render(request, 'predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
ERROR || 26-Jan-24 08:30:00 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 143, in predict_probability
    return render(request, 'predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
WARNING || 26-Jan-24 08:34:31 || Not Found: /predict/
ERROR || 26-Jan-24 08:34:40 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 143, in predict_probability
    return render(request, 'predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
INFO || 26-Jan-24 08:35:14 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 08:35:19 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.predict_probability didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 08:37:12 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:37:42 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
ERROR || 26-Jan-24 08:37:49 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'predict.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predict.html
INFO || 26-Jan-24 08:40:18 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 08:40:27 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 08:41:09 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'predicted_prob.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
INFO || 26-Jan-24 08:43:30 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 08:43:53 || Not Found: /recommend_courses/
ERROR || 26-Jan-24 08:44:08 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'predicted_prob.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
INFO || 26-Jan-24 08:45:03 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 08:45:17 || Not Found: /predict/predict_data/
WARNING || 26-Jan-24 08:46:13 || Not Found: /predict/predict_data/
WARNING || 26-Jan-24 08:46:42 || Not Found: /predict/predict_data/
WARNING || 26-Jan-24 08:47:40 || Not Found: /predict/predict_data/
WARNING || 26-Jan-24 08:47:45 || Not Found: /predict/predict_data/
ERROR || 26-Jan-24 08:55:15 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'academia_app/predicted_prob.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'predict_probability' not found. 'predict_probability' is not a valid view function or pattern name.
ERROR || 26-Jan-24 08:55:21 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'academia_app/predicted_prob.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'predict_probability' not found. 'predict_probability' is not a valid view function or pattern name.
INFO || 26-Jan-24 08:59:40 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:01:06 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:07:19 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 09:08:55 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:09:42 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:11:06 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 09:11:17 || Not Found: /predict_probability//
INFO || 26-Jan-24 09:11:35 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
WARNING || 26-Jan-24 09:11:39 || Not Found: /predict_probability//
WARNING || 26-Jan-24 09:11:51 || Not Found: /predict_probability/
INFO || 26-Jan-24 09:11:58 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
ERROR || 26-Jan-24 09:12:12 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 145, in predict_probability
    return render(request, 'predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
INFO || 26-Jan-24 09:13:11 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
WARNING || 26-Jan-24 09:13:15 || Not Found: /predict_probability/
WARNING || 26-Jan-24 09:14:30 || Not Found: /predict_probability/
WARNING || 26-Jan-24 09:14:32 || Not Found: /predict_probability/
WARNING || 26-Jan-24 09:14:33 || Not Found: /predict_probability/
INFO || 26-Jan-24 09:14:48 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
ERROR || 26-Jan-24 09:14:53 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 145, in predict_probability
    return render(request, 'predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: predicted_prob.html
INFO || 26-Jan-24 09:16:24 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 09:17:00 || Not Found: /predict_probability//
WARNING || 26-Jan-24 09:17:30 || Not Found: /predict_probability//
ERROR || 26-Jan-24 09:18:30 || Internal Server Error: /predict_probability/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 145, in predict_probability
    return render(request, 'academia_app/predicted_prob.html')
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: academia_app/predicted_prob.html
ERROR || 26-Jan-24 09:18:38 || Internal Server Error: /predict/
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\proacted\AIacademia\academia_app\views.py", line 92, in predict
    return render(request, 'academia_app/predicted_prob.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: academia_app/predicted_prob.html
INFO || 26-Jan-24 09:19:07 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 09:19:18 || Not Found: /predict/predict_probability
INFO || 26-Jan-24 09:20:25 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
WARNING || 26-Jan-24 09:20:36 || Not Found: /predict/predict_probability
INFO || 26-Jan-24 09:21:19 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:21:51 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 09:22:12 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
WARNING || 26-Jan-24 09:22:19 || Not Found: /predict/predict_probability
WARNING || 26-Jan-24 09:22:34 || Not Found: /predict/predict_probability
INFO || 26-Jan-24 09:23:13 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
ERROR || 26-Jan-24 09:23:19 || Internal Server Error: /predict/predict_probability
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/predict/predict_probability/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO || 26-Jan-24 09:23:57 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 09:25:25 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
ERROR || 26-Jan-24 09:25:36 || Internal Server Error: /predict/predict_probability
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/predict/predict_probability/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR || 26-Jan-24 09:25:42 || Internal Server Error: /predict/predict_probability
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/predict/predict_probability/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR || 26-Jan-24 09:28:35 || Internal Server Error: /predict/predict_probability
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/predict/predict_probability/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR || 26-Jan-24 09:28:40 || Internal Server Error: /predict/predict_probability
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to 127.0.0.1:8000/predict/predict_probability/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
INFO || 26-Jan-24 09:28:51 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
WARNING || 26-Jan-24 09:28:53 || Not Found: /predict/predict_probability
INFO || 26-Jan-24 09:32:50 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
WARNING || 26-Jan-24 09:33:05 || Not Found: /predict/predict_probability
WARNING || 26-Jan-24 09:34:25 || Not Found: /predict/predict_probability
INFO || 26-Jan-24 10:14:15 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:14:42 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:15:43 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:16:29 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:17:52 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:18:05 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:19:34 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 10:19:47 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 10:21:08 || C:\Users\Simon\proacted\AIacademia\academia_app\urls.py changed, reloading.
INFO || 26-Jan-24 10:24:17 || Beginning to run the recommender script
INFO || 26-Jan-24 10:24:17 || Recommender model loaded and running
INFO || 26-Jan-24 10:24:17 || Processing request...
INFO || 26-Jan-24 10:24:57 || Recommender system has run
ERROR || 26-Jan-24 10:24:57 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 10:25:46 || Beginning to run the recommender script
INFO || 26-Jan-24 10:25:46 || Recommender model loaded and running
INFO || 26-Jan-24 10:25:46 || Processing request...
INFO || 26-Jan-24 10:26:21 || Recommender system has run
ERROR || 26-Jan-24 10:26:21 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 10:27:29 || Beginning to run the recommender script
INFO || 26-Jan-24 10:27:29 || Recommender model loaded and running
INFO || 26-Jan-24 10:27:29 || Processing request...
INFO || 26-Jan-24 10:28:07 || Recommender system has run
ERROR || 26-Jan-24 10:28:07 || Internal Server Error: /recommend_courses
Traceback (most recent call last):
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "C:\Users\Simon\AppData\Roaming\Python\Python311\site-packages\django\core\handlers\base.py", line 332, in check_response
    raise ValueError(
ValueError: The view academia_app.views.recommend_courses didn't return an HttpResponse object. It returned None instead.
INFO || 26-Jan-24 10:28:34 || C:\Users\Simon\proacted\AIacademia\academia_app\views.py changed, reloading.
INFO || 26-Jan-24 10:28:43 || Beginning to run the recommender script
INFO || 26-Jan-24 10:28:43 || Recommender model loaded and running
INFO || 26-Jan-24 10:28:43 || Processing request...
INFO || 26-Jan-24 10:29:23 || Recommender system has run
INFO || 28-Jan-24 17:06:41 || Recommender model loaded and running
INFO || 28-Jan-24 17:06:41 || Processing request...
INFO || 28-Jan-24 17:14:48 || Recommender model loaded and running
INFO || 28-Jan-24 17:14:48 || Processing request...
INFO || 28-Jan-24 17:15:38 || Recommender model loaded and running
INFO || 28-Jan-24 17:15:38 || Processing request...
INFO || 28-Jan-24 17:17:11 || Recommender model loaded and running
INFO || 28-Jan-24 17:17:11 || Processing request...
INFO || 28-Jan-24 17:18:42 || Recommender model loaded and running
INFO || 28-Jan-24 17:18:42 || Processing request...
INFO || 28-Jan-24 17:28:10 || Recommender model loaded and running
INFO || 28-Jan-24 17:28:10 || Processing request...
INFO || 28-Jan-24 17:40:06 || Recommender model loaded and running
INFO || 28-Jan-24 17:40:06 || Processing request...
INFO || 28-Jan-24 17:48:17 || Recommender model loaded and running
INFO || 28-Jan-24 17:48:17 || Processing request...
INFO || 28-Jan-24 17:48:45 || Recommender model loaded and running
INFO || 28-Jan-24 17:48:45 || Processing request...
INFO || 28-Jan-24 17:49:06 || Recommender model loaded and running
INFO || 28-Jan-24 17:49:06 || Processing request...
INFO || 28-Jan-24 17:50:04 || Recommender model loaded and running
INFO || 28-Jan-24 17:50:04 || Processing request...
INFO || 28-Jan-24 17:50:50 || Recommender model loaded and running
INFO || 28-Jan-24 17:50:50 || Processing request...
INFO || 28-Jan-24 17:52:31 || Recommender model loaded and running
INFO || 28-Jan-24 17:52:31 || Processing request...
INFO || 31-Jan-24 05:42:57 || Recommender model loaded and running
INFO || 31-Jan-24 05:42:57 || Processing request...
INFO || 31-Jan-24 05:45:56 || Recommender model loaded and running
INFO || 31-Jan-24 05:45:56 || Processing request...
INFO || 31-Jan-24 05:46:41 || Recommender model loaded and running
INFO || 31-Jan-24 05:46:41 || Processing request...
INFO || 31-Jan-24 05:56:33 || Recommender model loaded and running
INFO || 31-Jan-24 05:56:33 || Processing request...
INFO || 31-Jan-24 06:05:07 || Recommender model loaded and running
INFO || 31-Jan-24 06:05:07 || Processing request...
INFO || 31-Jan-24 06:09:49 || Recommender model loaded and running
INFO || 31-Jan-24 06:09:49 || Processing request...
INFO || 02-Feb-24 06:18:36 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:19:03 || Successfully vectorized student input...
INFO || 02-Feb-24 06:23:48 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:24:07 || Successfully vectorized student input...
INFO || 02-Feb-24 06:32:06 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:32:28 || Successfully vectorized student input...
INFO || 02-Feb-24 06:36:12 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:36:33 || Successfully vectorized student input...
INFO || 02-Feb-24 06:49:45 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:49:56 || Successfully vectorized student input...
INFO || 02-Feb-24 06:50:58 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:51:08 || Successfully vectorized student input...
INFO || 02-Feb-24 06:54:06 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:54:17 || Successfully vectorized student input...
INFO || 02-Feb-24 06:54:52 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:55:03 || Successfully vectorized student input...
INFO || 02-Feb-24 06:55:44 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:55:55 || Successfully vectorized student input...
INFO || 02-Feb-24 06:58:29 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:58:39 || Successfully vectorized student input...
INFO || 02-Feb-24 06:59:47 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 06:59:57 || Successfully vectorized student input...
INFO || 02-Feb-24 07:00:59 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:01:09 || Successfully vectorized student input...
INFO || 02-Feb-24 07:03:49 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:03:59 || Successfully vectorized student input...
INFO || 02-Feb-24 07:13:27 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:13:37 || Successfully vectorized student input...
INFO || 02-Feb-24 07:14:29 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:14:40 || Successfully vectorized student input...
INFO || 02-Feb-24 07:15:21 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:15:32 || Successfully vectorized student input...
INFO || 02-Feb-24 07:17:22 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:17:32 || Successfully vectorized student input...
INFO || 02-Feb-24 07:19:20 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:19:30 || time recommender model has used: 11.861460447311401
INFO || 02-Feb-24 07:21:15 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:21:26 || time recommender model has used: 12.160961151123047
INFO || 02-Feb-24 07:24:28 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:24:39 || time recommender model has used: 12.081559658050537
INFO || 02-Feb-24 07:32:00 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:32:11 || time recommender model has used: 12.439636945724487
INFO || 02-Feb-24 07:35:19 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:35:29 || time recommender model has used: 12.27060317993164
INFO || 02-Feb-24 07:36:43 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 02-Feb-24 07:36:53 || time recommender model has used: 12.057013273239136
INFO || 04-Feb-24 19:56:25 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 04-Feb-24 19:56:55 || time recommender model has used: 38.0347158908844
WARNING || 04-Feb-24 19:57:17 || Not Found: /favicon.ico
INFO || 04-Feb-24 19:58:14 || Beginning to run the recommender script
INFO || 04-Feb-24 19:58:14 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 04-Feb-24 19:58:44 || time recommender model has used: 146.59151935577393
INFO || 04-Feb-24 19:58:44 || Recommender system has run
INFO || 12-Feb-24 12:07:00 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 12-Feb-24 12:07:33 || time recommender model has used: 38.16014814376831
INFO || 12-Feb-24 12:07:46 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 12-Feb-24 12:08:03 || time recommender model has used: 18.790717363357544
INFO || 14-Feb-24 06:29:54 || S-Bert 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:29:54 || Load pretrained SentenceTransformer: all-MiniLM-L6-v2
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (1): huggingface.co:443
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (2): huggingface.co:443
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (3): huggingface.co:443
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (4): huggingface.co:443
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (5): huggingface.co:443
DEBUG || 14-Feb-24 06:29:54 || Starting new HTTPS connection (6): huggingface.co:443
DEBUG || 14-Feb-24 06:29:55 || Starting new HTTPS connection (7): huggingface.co:443
DEBUG || 14-Feb-24 06:29:55 || Starting new HTTPS connection (8): huggingface.co:443
INFO || 14-Feb-24 06:29:55 || Use pytorch device_name: cpu
INFO || 14-Feb-24 06:30:08 || Time taken by sbert model: 13.605860710144043
INFO || 14-Feb-24 06:31:45 || S-Bert 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:31:45 || Load pretrained SentenceTransformer: all-MiniLM-L6-v2
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (1): huggingface.co:443
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (2): huggingface.co:443
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (3): huggingface.co:443
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (4): huggingface.co:443
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (5): huggingface.co:443
DEBUG || 14-Feb-24 06:31:45 || Starting new HTTPS connection (6): huggingface.co:443
DEBUG || 14-Feb-24 06:31:46 || Starting new HTTPS connection (7): huggingface.co:443
DEBUG || 14-Feb-24 06:31:46 || Starting new HTTPS connection (8): huggingface.co:443
INFO || 14-Feb-24 06:31:46 || Use pytorch device_name: cpu
INFO || 14-Feb-24 06:31:57 || Time taken by sbert model: 11.895556926727295
INFO || 14-Feb-24 06:35:50 || S-Bert 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:35:50 || Load pretrained SentenceTransformer: all-MiniLM-L6-v2
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (1): huggingface.co:443
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (2): huggingface.co:443
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (3): huggingface.co:443
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (4): huggingface.co:443
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (5): huggingface.co:443
DEBUG || 14-Feb-24 06:35:50 || Starting new HTTPS connection (6): huggingface.co:443
DEBUG || 14-Feb-24 06:35:51 || Starting new HTTPS connection (7): huggingface.co:443
DEBUG || 14-Feb-24 06:35:51 || Starting new HTTPS connection (8): huggingface.co:443
INFO || 14-Feb-24 06:35:51 || Use pytorch device_name: cpu
INFO || 14-Feb-24 06:43:45 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:44:09 || time recommender model has used: 27.704192638397217
WARNING || 14-Feb-24 06:45:05 || Not Found: /favicon.ico
INFO || 14-Feb-24 06:48:47 || Beginning to run the proacted recommender script
INFO || 14-Feb-24 06:48:47 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:49:03 || time recommender model has used: 321.6681499481201
INFO || 14-Feb-24 06:49:06 || S-Bert 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:49:06 || Load pretrained SentenceTransformer: all-MiniLM-L6-v2
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (1): huggingface.co:443
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (2): huggingface.co:443
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (3): huggingface.co:443
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (4): huggingface.co:443
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (5): huggingface.co:443
DEBUG || 14-Feb-24 06:49:06 || Starting new HTTPS connection (6): huggingface.co:443
DEBUG || 14-Feb-24 06:49:07 || Starting new HTTPS connection (7): huggingface.co:443
DEBUG || 14-Feb-24 06:49:07 || Starting new HTTPS connection (8): huggingface.co:443
INFO || 14-Feb-24 06:49:07 || Use pytorch device_name: cpu
INFO || 14-Feb-24 06:49:13 || Time taken by sbert model: 6.248710632324219
INFO || 14-Feb-24 06:49:13 || Recommender system has run
INFO || 14-Feb-24 06:52:40 || Beginning to run the proacted recommender script
INFO || 14-Feb-24 06:52:40 || Pro-Act-Ed 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:52:54 || time recommender model has used: 552.6749496459961
INFO || 14-Feb-24 06:52:54 || S-Bert 2024 Recommender Engine Initialized
INFO || 14-Feb-24 06:52:54 || Load pretrained SentenceTransformer: all-MiniLM-L6-v2
DEBUG || 14-Feb-24 06:52:54 || Starting new HTTPS connection (9): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (10): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (11): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (12): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (13): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (14): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (15): huggingface.co:443
DEBUG || 14-Feb-24 06:52:55 || Starting new HTTPS connection (16): huggingface.co:443
INFO || 14-Feb-24 06:52:55 || Use pytorch device_name: cpu
INFO || 14-Feb-24 06:53:00 || Time taken by sbert model: 5.043795824050903
INFO || 14-Feb-24 06:53:00 || Recommender system has run
